Revamp dotfiles using antidote (#3)
* :boom: Revamp

* :bug: :sparkles:

* :recycle:

* :bug: oops

* :sparkles: Aliases

* :sparkles: Always show exit status

* :sparkles: pnpm

* :boom: Right

* Finally got completions to work??

This is very scuffed...

* Screw poetry

* :sparkles: Nice completion styles

Taken some parts from Prezto

* :sparkles: Configure FZF default command

* :bulb: :memo: docs

* :sparkles: fzf plugin

* :memo: FZF

* :bug: Some people don't have compinit?

* :sparkles: Better brew

* :sparkles: Added JetBrains toolbox

* :poop: Updated setup script a bit

TODO: reorganize

* Pipx fix

* :fire: Cleaned Brewfile

* :fire: no git delta for now

* :memo: README changes

* Brewfile changes

* Setup vim

* :sparkles: vim

* Which, what, where??

* Tealdeer!

* :sparkles: JetBrains

* Rust!

* :bug: Fix path

* pnpm...

* Git aliases

* :spakles: Homebrew packages

* RubyGems

* Completely fixed completions

* Re organize

* Trash

* :sparkles: pnpm completions

* Changed setup script

* :sparkles: More plugins

* :sparkles: asdf direnv

* Direnv config

* :sparkles: Golang

* Updated Brewfile

* Path bin

* :bug: Fixed double completion glitch

* More VSCode extensions + Brew stuff

* Add unquarantine alias to zshrc/aliases.zsh

* Atuin!

* Remove bloat!

* setup script todos

* Setup script v1

* setup script: Forgot about asdf

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -1,38 +1,26 @@
 #!/usr/bin/env bash
 
-setup_python() {
-    if command -v pyenv &> /dev/null
-    then
-        return
-    fi
-    brew install openssl readline sqlite3 xz zlib
-    curl -sSf https://pyenv.run | bash  # install pyenv
-    # XXX: How to reload shell?
-    szrc
-    # FIXME: No need for these CFLAGS, etc if we have the aliases.zsh loaded
-    CFLAGS="-I$(brew --prefix xz)/include" LDFLAGS="-L$(brew --prefix xz)/lib" PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.10.4
-    pyenv global 3.10.4
-    python -m ensurepip
-    install_pipx
+install_antidote() {
+    git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-$HOME}/.antidote
 }
-setup_omz() {
-    if command -v omz &> /dev/null
-    then
-        return
-    fi
-    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-    # TODO: Install custom plugins
-
+reset_zshrc() {
+    echo "source $HOME/dotfiles/zshrc/index.zsh" > ~/.zshrc
+    source ~/.zshrc
 }
-setup_homebrew() {
+install_homebrew() {
     if command -v brew &> /dev/null
     then
+        echo "Homebrew already installed"
         return
     fi
-    git clone --depth=1 https://github.com/Homebrew/brew.git ~/homebrew
-    eval "$(~/homebrew/bin/brew shellenv)"
-    brew update
-    (cd ~ && brew bundle install)
+    echo "Installing homebrew"
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+}
+setup_homebrew() {
+    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
+    eval "$(/opt/homebrew/bin/brew shellenv)"
+    cd ~/dotfiles && brew bundle install
+    /opt/homebrew/opt/fzf/install
 }
 install_pipx() {
     if command -v pipx &> /dev/null
@@ -42,22 +30,96 @@ install_pipx() {
     pip install pipx
     pipx install pipx
     pip uninstall pipx --yes
+}
+setup_pipx() {
     cat $HOME/dotfiles/requirements.txt | xargs -n 1 pipx install
 }
-main() {
-    echo "Ok im not done yet"
-    return
-    git clone --depth=1 https://github.com/ThatXliner/dotfiles.git ~/dotfiles
-    echo "source $HOME/dotfiles/zshrc/index.zsh" > ~/.zshrc
+install_asdf() {
+    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
+    . "$HOME/.asdf/asdf.sh"  # For now
+}
+setup_asdf() {
+    asdf plugin add python
+    asdf install python latest
+    asdf global python latest
+    asdf install python latest:3.11  # For pipx for now
 
-    xcode-select --install || echo "Xcode already set up!"
-    ln -s ~/dotfiles/Brewfile Brewfile
+    asdf plugin add nodejs
+    asdf install nodejs latest
+    asdf global nodejs latest
+
+    asdf plugin-add direnv
+    asdf direnv setup --shell zsh --version system
+    asdf global direnv system
+}
+install_js_stuff() {
+    curl -fsSL https://get.pnpm.io/install.sh | sh -
+    curl -fsSL https://bun.sh/install | bash
+}
+setup_js_stuff() {
+    pnpm install -g node-gyp  # XXX
+    pnpm install-completion zsh
+    bun add --global trash-cli
+}
+setup_vim() {
+    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+    ln -s .vimrc ~/.vimrc
+}
+install_rust() {
+    # Rustup > asdf
+    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+}
+setup_config() {
+    # Git aliases
+    git config --global alias.aliases 'config --get-regexp alias'
+    git config --global alias.abort-merge 'reset --hard HEAD'
+    git config --global alias.uncommit 'reset --soft HEAD^'
+    git config --global alias.unstage 'reset --'
+    # alias.cleanup-branches !curl -s https://raw.githubusercontent.com/paulmillr/dotfiles/master/git-extras/git-cleanup.rb | ruby -
+    # alias.reset-to-remote reset --hard @{u}
+    # alias.l log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
+
+    # Use multiline prompt
+    ln -s ~/dotfiles/prompts/multi.zsh ~/.p10k.zsh
+
+    ln -s ~/dotfiles/.vimrc ~/.vimrc
+
+    echo "[global]\nload_dotenv = true" > ~/.config/direnv/direnv.toml
+
+    setup_js_stuff
+    setup_vim
+}
+install_custom_direnv() {
+    git clone --depth=1 https://github.com/ThatXliner/direnv.git ~/temp
+    cd ~/temp
+    git switch support-extra-env-files
+    make
     mkdir -p ~/bin
+    cp direnv ~/bin/direnv
+    rm -rf ~/temp
+}
+# TODO: download the visual stuff too
+main() {
+    # Remove "last login" message
+    touch ~/.hushlogin
+    # Install Xcode command line tools
+    xcode-select --install || echo "Xcode already set up!"
+    # Clone my dotfiles
+    git clone --depth=1 https://github.com/ThatXliner/dotfiles.git ~/dotfiles
+    install_asdf
+    install_antidote
+    install_homebrew
     setup_homebrew
-    setup_python
-    # TODO: Setup Node with nvm
-    # install pipx, install the stuff in requirements.txt
-    # install oh-my-zsh and plugins and the custom plugins
-    # install powerlevel10k
+    gum confirm "Please install Go from https://go.dev before continuing"
+    install_custom_direnv
+    setup_asdf
+    reset_zshrc
+
+    install_pipx
+    install_js_stuff
+    reset_zshrc
+
+    setup_config
+    reset_zshrc
 }
 main
